### PR TITLE
php8.3

### PR DESCRIPTION
**Pull request by orhtej2**
## Problem

- PHP 7.4 is EOL

## Solution

- Use the latest 🤷 

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by orhtej2** [comment]
!testme

**Comment by ericgaspar** [comment]
Is it mergeable?

**Comment by orhtej2** [comment]
!testme

**Comment by orhtej2** [comment]
This now properly installs and basic browsing seems OK, but I've noticed at least one sharp edge around PHP 8.0 support so not sure if its officially supported upstream 🤷

**Comment by orhtej2** [comment]
Asked over at xech/agora-project#34

**Comment by orhtej2** [comment]
!testme

**Pull request merged**
